name: Generate Stats Images and Merge to Master

on:
  push:
    branches: [ mach ]
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3
      with:
        ref: develop

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # Commit changes to the mach branch
    - name: Commit changes to mach
      run: |
        git config --global user.name "Mach-Levi"
        git config --global user.email "machlevi2021@gmail.com"
        git add .
        git commit -m 'Update files with the latest languages.
        
        
        Co-authored-by: Mach-Levi <machlevi2021@gmail.com>
        Co-authored-by: omololevy <cotechlevy@gmail.com>'
        git push origin mach

    # Merge develop branch into master branch
    - name: Merge to master
      run: |
        git fetch origin
        git checkout master
        git merge develop --no-ff -m "Merge develop branch into master"
        git push origin master
