name: Generate Stats Images and Merge to Master

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/25 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out repository under $GITHUB_WORKSPACE, so the job can access it
    - uses: actions/checkout@v3
      with:
        ref: main

    # Run using Python 3.8 for consistency and aiohttp
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    # Install dependencies with `pip`
    - name: Install requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt

    # Generate all statistics images
    - name: Generate images
      run: |
        python3 --version
        python3 generate_images.py
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EXCLUDED: ${{ secrets.EXCLUDED }}
        EXCLUDED_LANGS: ${{ secrets.EXCLUDED_LANGS }}
        EXCLUDE_FORKED_REPOS: true

    # Commit changes to the main branch
    - name: Commit changes to main
      run: |
        git config --global user.name "Mach-Levi"
        git config --global user.email "machlevi2021@gmail.com"
        git add .
        git commit -m 'Update files with the latest languages.
        
        
        
        Co-authored-by: Mach-Levi <machlevi2021@gmail.com>
        Co-authored-by: MihalczGabor <gabor.mihalcz@gabinnyogroup.ws>
        Co-authored-by: omololevy <cotechlevy@gmail.com>'
        git push origin main

    # Merge develop branch into master branch
#     - name: Merge to master
#       run: |
#         git fetch origin
#         git checkout master
#         git merge main --no-ff -m "Merge main branch into master"
#         git push origin master
        
    # Create pull request for merging develop branch into master branch
    - name: Create pull request
      uses: Mach-Levi/create-pull-request@v3
      with:
        title: 'Merge main into master'
        commit-message: 'Merge main branch into master'
        branch: master
        body: 'This pull request by a GitHub action.'
        labels: 'automated'
        token: ${{ secrets.GITHUB_TOKEN }}
